# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
Variables:
  raise:
    salary:
      # Percentage to raise salaries.
      percentage: "5"
      # The probability (as a percentage going from 0-100) that a person receives a raise of their salary.
      probability: "5"
